/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package adrover.trainingtime.views;

import adrover.trainingtime.Main;
import adrover.trainingtime.dataaccess.DataAccess;
import adrover.trainingtime.dtos.Usuari;
import at.favre.lib.crypto.bcrypt.BCrypt;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class LoginDialog extends javax.swing.JDialog {

    private Main jFrame;
    private Usuari loggedUser;

    /**
     * Creates new form LoginDialog
     */
    public LoginDialog(java.awt.Frame parent, boolean modal, Main mainFrame) {
        super(parent, modal);
        initComponents();
        this.setSize(800, 400);
        this.setBounds(0, 0, 800, 400);
        this.jFrame = (Main) mainFrame; // Asignar la referencia de Main
        setLocationRelativeTo(this);
       
    }

    public Usuari getloggedUser() {
        return this.loggedUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jTextFieldEmailLogin = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jPasswordFieldPasswordLogin = new javax.swing.JPasswordField();
        jLabelMessageSuccess = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setBounds(new java.awt.Rectangle(0, 0, 500, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 400));
        jPanel1.setLayout(null);

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 204));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanelLogin.setMinimumSize(new java.awt.Dimension(580, 310));
        jPanelLogin.setLayout(null);

        jTextFieldEmailLogin.setText("a@b.c");
        jTextFieldEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jTextFieldEmailLogin);
        jTextFieldEmailLogin.setBounds(32, 71, 286, 33);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonLogin);
        jButtonLogin.setBounds(250, 240, 72, 23);

        jPasswordFieldPasswordLogin.setText("string");
        jPasswordFieldPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jPasswordFieldPasswordLogin);
        jPasswordFieldPasswordLogin.setBounds(32, 156, 290, 33);
        jPanelLogin.add(jLabelMessageSuccess);
        jLabelMessageSuccess.setBounds(0, 0, 0, 0);

        jLabel3.setText("Insert Email");
        jPanelLogin.add(jLabel3);
        jLabel3.setBounds(32, 43, 280, 16);

        jLabel4.setText("Insert Password");
        jPanelLogin.add(jLabel4);
        jLabel4.setBounds(32, 122, 290, 16);

        jPanel1.add(jPanelLogin);
        jPanelLogin.setBounds(120, 140, 580, 310);

        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogout);
        jButtonLogout.setBounds(10, 20, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jPasswordFieldPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordLoginActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        DataAccess da = new DataAccess();
        Usuari usuari = da.getUsuari(jTextFieldEmailLogin.getText());
        if (usuari != null) {
            char[] passordToVerify = jPasswordFieldPasswordLogin.getPassword();
            String userPasswordHashInDB = usuari.getPasswordHash();
            var result = BCrypt.verifyer().verify(passordToVerify, userPasswordHashInDB);

            if (result.verified) {
                JOptionPane.showMessageDialog(this, "Login success. Welcome " + usuari.getNom() + "!");
                loggedUser = usuari; // Guardar el usuario logueado

                // Mostrar el panel de usuarios en el JFrame principal
                jFrame.showListUsers(loggedUser); // Mostrar el panel de usuarios con el instructor
                dispose(); // Cerrar el diálogo de login
            } else {
                JOptionPane.showMessageDialog(this, "Error: invalid password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error: user not found");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jTextFieldEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessageSuccess;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldPasswordLogin;
    private javax.swing.JTextField jTextFieldEmailLogin;
    // End of variables declaration//GEN-END:variables
}
