/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adrover.trainingtime;

import adrover.trainingtime.dataaccess.DataAccess;
import adrover.trainingtime.dtos.Usuaris;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author nuria
 */

public class ListUsers extends javax.swing.JPanel {

    private Main jFrameMain;
    private DataAccess da = new DataAccess();
    private Usuaris instructor;

    /**
     * Creates new form ListUsuaris
     */
    public ListUsers(Main jFrameMain, Usuaris instructor1) {
        this.jFrameMain = jFrameMain;
        this.instructor = instructor;
        this.da = new DataAccess();
        this.setSize(600, 400);
        this.setLayout(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonUsers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList<>();
        jPanelWorkouts = new javax.swing.JPanel();
        jButtonAddTrain = new javax.swing.JButton();
        jButtonModifTrain = new javax.swing.JButton();
        jButtonWorkouts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListWorks = new javax.swing.JList<>();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("USERS"));

        jButtonUsers.setText("Show Users");
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jListUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListUsers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButtonUsers))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanelWorkouts.setBorder(javax.swing.BorderFactory.createTitledBorder("WORKOUTS"));

        jButtonAddTrain.setText("Add");
        jButtonAddTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTrainActionPerformed(evt);
            }
        });

        jButtonModifTrain.setText("Edit");

        jButtonWorkouts.setText("Workouts");
        jButtonWorkouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkoutsActionPerformed(evt);
            }
        });

        jListWorks.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListWorks);

        javax.swing.GroupLayout jPanelWorkoutsLayout = new javax.swing.GroupLayout(jPanelWorkouts);
        jPanelWorkouts.setLayout(jPanelWorkoutsLayout);
        jPanelWorkoutsLayout.setHorizontalGroup(
            jPanelWorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWorkoutsLayout.createSequentialGroup()
                .addGroup(jPanelWorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelWorkoutsLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelWorkoutsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonWorkouts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModifTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanelWorkoutsLayout.setVerticalGroup(
            jPanelWorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWorkoutsLayout.createSequentialGroup()
                .addGroup(jPanelWorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWorkoutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddTrain)
                        .addComponent(jButtonModifTrain))
                    .addComponent(jButtonWorkouts))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jPanelWorkouts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWorkouts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setUsuari(Usuaris usuari) {
        this.instructor = usuari;

    }
    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsersActionPerformed
        // Obtener el ID del instructor logueado
        int instructorId = instructor.getId();
        ArrayList<Usuaris> usuaris = da.getUsuaris();
        DefaultListModel<String> listaUsuaris = new DefaultListModel<>();

        // Filtrar usuarios para mostrar solo los entrenados por el instructor actual
        for (Usuaris u : usuaris) {
            listaUsuaris.addElement(u.toString());
        }
        jListUsers.setModel(listaUsuaris);

        jButtonWorkouts.setVisible(true);
        jButtonUsers.setVisible(false);
    }//GEN-LAST:event_jButtonUsersActionPerformed

    private void jButtonWorkoutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkoutsActionPerformed
        jButtonUsers.setVisible(true);
        jButtonWorkouts.setVisible(false);
    }//GEN-LAST:event_jButtonWorkoutsActionPerformed

    private void jButtonAddTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTrainActionPerformed
       /* // Get the selected user from the list
        String selectedUserName = jListUsers.getSelectedValue(); // Assuming 'jListUsers' is the JList showing users

        // Check if a user is selected
        if (selectedUserName != null) {
            // Find the Usuaris object corresponding to the selected user
            Usuaris selectedUser = instructor.getUserByName(selectedUserName); // Assuming method exists

            // Open the CreateWorkoutDialog to add a workout for the selected user
            if (selectedUser != null) {
                CreateWorkoutDialog workoutDialog = new CreateWorkoutDialog(jFrameMain, selectedUser);
                workoutDialog.setVisible(true); // Show the dialog

                // After closing the dialog, refresh the workout list for the selected user
                updateWorkoutsList(selectedUser);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a user first.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    private void updateWorkoutsList(Usuaris selectedUser) {
        ArrayList<String> workouts = selectedUser.getWorkouts(); // Assuming getWorkouts() returns the list of workouts
        DefaultListModel<String> workoutsListModel = new DefaultListModel<>();

        for (String workout : workouts) {
            workoutsListModel.addElement(workout);
        }

        jListWorks.setModel(workoutsListModel); // Update the workout list model with the new data
    }*/

    }//GEN-LAST:event_jButtonAddTrainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTrain;
    private javax.swing.JButton jButtonModifTrain;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JButton jButtonWorkouts;
    private javax.swing.JList<String> jListUsers;
    private javax.swing.JList<String> jListWorks;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelWorkouts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
