/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adrover.trainingtime;

import adrover.trainingtime.dtos.Usuari;
import adrover.trainingtime.LoginDialog;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class MainJPanel extends javax.swing.JPanel {

    private Main main= null;
    /**
     * Creates new form MainJPanel
     */
    public MainJPanel(Main mainJFrame) {
        initComponents();
        this.setSize(800,800);
        main= mainJFrame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWeb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAccess = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(null);

        jLabelWeb.setForeground(new java.awt.Color(0, 0, 0));
        jLabelWeb.setText("Visit our website for more information");
        jLabelWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWebMouseClicked(evt);
            }
        });
        add(jLabelWeb);
        jLabelWeb.setBounds(240, 490, 220, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TrainingTime logo (1).png"))); // NOI18N
        jLabel1.setText("Logo");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));
        add(jLabel1);
        jLabel1.setBounds(180, 30, 329, 331);

        jButtonAccess.setText("Access");
        jButtonAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccessActionPerformed(evt);
            }
        });
        add(jButtonAccess);
        jButtonAccess.setBounds(290, 410, 115, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelWebMouseClicked
        try {
            String url = "www.trainingtimeweb.com";
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace(); // Handle exceptions appropriately
            JOptionPane.showMessageDialog(this, "Failed to open the webpage.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelWebMouseClicked

    private void jButtonAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccessActionPerformed
        // Lógica para el login
        LoginDialog loginDialog = new LoginDialog(main, true, main);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_jButtonAccessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWeb;
    // End of variables declaration//GEN-END:variables
}
